### ISSUE TITLE
demo.py error on startup

### ISSUE THREAD

**Issue by aaps** [SirFroweey/PyDark#6]
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    position=(100, 100),
  File "demo.py", line 65, in **init**
    self.default_image = pygame.image.load(default_image).convert_alpha()
pygame.error: Couldn't open input.png

**Comment by adnathanail** [comment]
I have this too, any help?
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    position=(100, 100),
  File "demo.py", line 65, in **init**
    self.default_image = pygame.image.load(default_image).convert_alpha()
pygame.error: Couldn't open input.png

**Comment by aaps** [comment]
So yeah that was a while ago:
i didnt use that multyplayer network suff after that.

look at https://github.com/aaps/stardog/tree/multiplayer

to see what i used !

Aat

**Comment by JerzySpendel** [comment]
This project seems to be dead :(

**Comment by PMLyf** [comment]
Yeah we need to revive this.

**Comment by SirFroweey** [comment]
@PMLyf I would but I've been busy with work and frankly, to be honest, I've shifted focus onto using an already fully-featured Game engine called GameMaker. It's pretty damn powerful for making 2D multiplayer games. It also speeds up development time by a large margin. I understand that you guys may want to continue using PyDark, but it's easier to hit the ground up running with an already existing game engine.

**Comment by SirFroweey** [comment]
@adnathanail You need to supply a text-input file, that demo was using a PNG image file named input.png. So you should supply one.

**Comment by SirFroweey** [comment]
@PMLyf We are still making Persistent Empires! We are just using GameMaker now, contact me on Skype for details as I want to bring you into this project.

**Comment by PMLyf** [comment]
Will do bro!
